exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

target-version = "py313"

[lint]
select = ["ALL"]
ignore = [
  "COM812", # Ignore due to conflict with Ruff formatter
  "ISC001", # Ignore due to conflict with Ruff formatter
  "D104",   # Ignore missing docstring in public package
  "D100",   # Ignore missing docstring in public module
  "D203",   # Ignoring due to incompatibility with Ruff D211
  "D212",   # Ignoring due to incompatibility with Ruff D213
]

fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
