target-version = "py314"

[lint]
select = ["ALL"]
ignore = [
  "COM812", # Ignore due to conflict with Ruff formatter
  "ISC001", # Ignore due to conflict with Ruff formatter
  "D104",   # Ignore missing docstring in public package
  "D100",   # Ignore missing docstring in public module
  "D203",   # Ignoring due to incompatibility with Ruff D211
  "D212",   # Ignoring due to incompatibility with Ruff D213
]

fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
