name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  clean-caches:
    name: Clean Caches
    permissions:
      contents: read
    uses: JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml@75ceb782a5815a98162de1321c852df74830a493 # v2025.05.24.01
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
