name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/other-configurations/labels.yml
  workflow_dispatch:

permissions: {}

jobs:
  configure-labels:
    permissions:
      contents: read
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-sync-labels.yml@75ceb782a5815a98162de1321c852df74830a493 # v2025.05.24.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
